export { Hero } from "./Hero";
export { Faq } from "./Faq";
export { Feature } from "./Feature";
export { Footer } from "./Footer";
export { Navbar } from "./Navbar";
export { Pricing } from "./Pricing";
export { Testimonial } from "./Testimonial";
export { TrustedBy } from "./TrustedBy";
export { WhoItsFor } from "./WhoItsFor";
